#!/bin/sh
#
# @name Gazebo x500 lidar 2d + down
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_2d_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Use rangefinder as primary height source
param set-default EKF2_HGT_REF 2
param set-default EKF2_RNG_CTRL 1
