#!/bin/sh
#
# @name Gazebo x500 lidar 2d + down
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_2d_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Indoor rangefinder altitude
param set-default EKF2_HGT_REF 2
param set-default EKF2_RNG_CTRL 2
param set-default MPC_ALT_MODE 1

# Disable battery failsafe in SITL
param set-default COM_LOW_BAT_ACT 0

# No RC/joystick in indoor SITL - disable RC loss failsafe
param set-default NAV_RCL_ACT 0
param set-default BAT_LOW_THR 0.05
param set-default BAT_CRIT_THR 0.02
param set-default BAT_EMERGEN_THR 0.01

# No GPS indoors - use external vision (SLAM) for horizontal position + yaw
# EKF2_EV_CTRL: bit0=horiz pos, bit3=yaw => 9
param set-default SIM_GZ_EN_GPS 0
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_EV_CTRL 9
